Caching allocators for host and device
cms-patatrack/pixeltrack-standalone pull request #260
Opened 2021-11-02 09:12 UTC by waredjeb

- Rebase of #248 

## Caching Allocator and Async Allocator Enabled
```
[patatrack02 pixeltrack-standalone]$ CUDA_VISIBLE_DEVICES=0 numactl -N 1 ./alpaka --cuda --numberOfThreads 8 --numberOfStreams 16 --validation --maxEvents 10000; echo; for N in 1 2 3 4; do CUDA_VISIBLE_DEVICES=0 numactl -N 1 ./alpaka --cuda --numberOfThreads 8 --numberOfStreams 16 --maxEvents 10000; done
Processing 10000 events, of which 16 concurrently, with 8 threads.
CountValidator: all 10000 events passed validation
 Average relative track difference 0.00088565 (all within tolerance)
 Average absolute vertex difference 0.0006 (all within tolerance)
Processed 10000 events in 1.472030e+01 seconds, throughput 679.334 events/s.

Processing 10000 events, of which 16 concurrently, with 8 threads.
Processed 10000 events in 4.990729e+00 seconds, throughput 2003.72 events/s.
Processing 10000 events, of which 16 concurrently, with 8 threads.
Processed 10000 events in 4.992631e+00 seconds, throughput 2002.95 events/s.
Processing 10000 events, of which 16 concurrently, with 8 threads.
Processed 10000 events in 4.986976e+00 seconds, throughput 2005.22 events/s.
Processing 10000 events, of which 16 concurrently, with 8 threads.
Processed 10000 events in 4.992776e+00 seconds, throughput 2002.89 events/s.
```
## Disabling the Caching Allocator and the Async Allocator
`make alpaka -j 10 CUDA_BASE=/usr/local/cuda-11.2 USER_CXXFLAGS="-DALPAKA_DISABLE_CACHING_ALLOCATOR -DALPAKA_DISABLE_ASYNC_ALLOCATOR"`

```
[patatrack02 pixeltrack-standalone]$ CUDA_VISIBLE_DEVICES=0 numactl -N 1 ./alpaka --cuda --numberOfThreads 8 --numberOfStreams 16 --validation --maxEvents 10000; echo; for N in 1 2 3 4; do CUDA_VISIBLE_DEVICES=0 numactl -N 1 ./alpaka --cuda --numberOfThreads 8 --numberOfStreams 16 --maxEvents 10000; done
Processing 10000 events, of which 16 concurrently, with 8 threads.
CountValidator: all 10000 events passed validation
 Average relative track difference 0.000888953 (all within tolerance)
 Average absolute vertex difference 0.0005 (all within tolerance)
Processed 10000 events in 4.884283e+01 seconds, throughput 204.738 events/s.

Processing 10000 events, of which 16 concurrently, with 8 threads.
Processed 10000 events in 4.017372e+01 seconds, throughput 248.919 events/s.
Processing 10000 events, of which 16 concurrently, with 8 threads.
Processed 10000 events in 4.029434e+01 seconds, throughput 248.174 events/s.
Processing 10000 events, of which 16 concurrently, with 8 threads.
Processed 10000 events in 4.101676e+01 seconds, throughput 243.803 events/s.
Processing 10000 events, of which 16 concurrently, with 8 threads.
Processed 10000 events in 3.935691e+01 seconds, throughput 254.085 events/s.
```

2021-11-02 09:44 UTC, fwyzard requested changes
First round of comments...

2021-11-02 09:44 UTC, fwyzard commented on src/alpaka/AlpakaCore/CachingDeviceAllocator.h
> +  struct CachingDeviceAllocator {
This class should be templated on the `Device` type:
```suggestion
  template <typename TDevice>
  struct CachingDeviceAllocator {
  public:
    using Device = TDevice;
```

2021-11-02 09:44 UTC, fwyzard commented on src/alpaka/AlpakaCore/CachingDeviceAllocator.h
> +                      const ::ALPAKA_ACCELERATOR_NAMESPACE::Device& device)
`::ALPAKA_ACCELERATOR_NAMESPACE::Device` should be replaced by the `Device` template type:
```suggestion
                      Device const& device)
```

2021-11-02 09:44 UTC, fwyzard commented on src/alpaka/AlpakaCore/CachingDeviceAllocator.h
> +      BlockDescriptor(::ALPAKA_ACCELERATOR_NAMESPACE::AlpakaDeviceBuf<std::byte> buffer)
`::ALPAKA_ACCELERATOR_NAMESPACE::AlpakaDeviceBuf<std::byte>` should be replaced by a buffer type that depends on the `Device` template parameter:
```suggestion
      using DeviceBuffer = alpaka::Buf<Device, std::byte, Dim1D, Idx>;
      ...
      BlockDescriptor(DeviceBuffer buffer)
```

2021-11-02 15:55 UTC, makortel commented on src/alpaka/AlpakaCore/CachingDeviceAllocator.h
> +        alpaka::prepareForAsyncCopy(search_key.buf);
What does `prepareForAsyncCopy()` do? I'd guess it to call `cudaHostRegister()` or similar under the hood for host memory.

Looking at the code I see this is a no-op for CUDA/HIP buffers
https://github.com/alpaka-group/alpaka/blob/ee525dbb1c3e71490a17df80e7d13b3067619b95/include/alpaka/mem/buf/BufUniformCudaHipRt.hpp#L408-L418
(so in principle this call would not be needed for the device allocator)

For host buffers it indeed ends up calling `cudaHostRegister()`
https://github.com/alpaka-group/alpaka/blob/ee525dbb1c3e71490a17df80e7d13b3067619b95/include/alpaka/mem/buf/BufCpu.hpp#L363-L378
https://github.com/alpaka-group/alpaka/blob/ee525dbb1c3e71490a17df80e7d13b3067619b95/include/alpaka/mem/buf/BufCpu.hpp#L269-L303

But given the
```cpp
#if(defined(ALPAKA_ACC_GPU_CUDA_ENABLED) && BOOST_LANG_CUDA) || (defined(ALPAKA_ACC_GPU_HIP_ENABLED) && BOOST_LANG_HIP)
```
the `cudaHostRegister()` is called only if the source file including this Alpaka header is compiled with `ALPAKA_ACC_GPU_CUDA_ENABLED` and compiling with `nvcc` (which we do when that macro is enabled). I'm afraid mixing that with code using `BufCpu.hpp` compiled without `ALPAKA_ACC_GPU_CUDA_ENABLED` would technically violate ODR.

I also see the definition of `alpaka::detail::BufCpuImpl` depends on these macros, in particular whether the `m_bPinned` member exists or not
https://github.com/alpaka-group/alpaka/blob/ee525dbb1c3e71490a17df80e7d13b3067619b95/include/alpaka/mem/buf/BufCpu.hpp#L103-L105

2021-11-02 15:55 UTC, makortel commented on src/alpaka/AlpakaCore/CachingDeviceAllocator.h
> +                            device)  ///< [in] The device to be associated with this allocation
What is the plan towards asynchronous (in a sense garbage-collecting) API?

2021-11-02 15:55 UTC, makortel commented on src/alpaka/AlpakaCore/deviceAllocatorStatus.h
> +      }
(just repeating) Given https://github.com/cms-patatrack/pixeltrack-standalone/blob/master/src/alpaka/AlpakaCore/getDevIndex.h this is not needed.

2021-11-02 15:55 UTC, makortel commented on src/alpaka/AlpakaCore/device_unique_ptr.h
> +          DeviceDeleter(::ALPAKA_ACCELERATOR_NAMESPACE::AlpakaDeviceBuf<TData> buffer) : buf{std::move(buffer)} {}
This class would need to be templated over Device.

2021-11-02 15:55 UTC, makortel commented on src/alpaka/AlpakaCore/device_unique_ptr.h
> +    }  // namespace device
Technically this violates ODR. Templating the `unique_ptr` also over Device and providing a specialization for `DevCudaRt` if `ALPAKA_ACC_GPU_CUDA_ENABLED` is defined would work. In longer term, I think, we should think about hiding the exact deleter type from the type of the `unique_ptr` (or just go directly to `shared_ptr` semantics).

2021-11-02 15:55 UTC, makortel commented on src/alpaka/AlpakaCore/device_unique_ptr.h
> +        }
The behavior of `Asynchronous` policy would be different from `cuda`, right?

2021-11-02 15:55 UTC, makortel commented on src/alpaka/AlpakaCore/CachingDeviceAllocator.h
> +                            device)  ///< [in] The device to be associated with this allocation
Do all scopes creating and destroying `unique_ptr`s have `alpaka::wait()` before the end of scope?

2022-02-01 14:45 UTC, fwyzard commented
reimplemented in #301

2022-02-01 14:45 UTC, closed without merging